### ISSUE TITLE
SHA vs RandomX

### ISSUE THREAD

**Issue by LucasMZReal** [altcha-org/altcha#11]
I haven't looked at the code much (I don't understand the languages used) however it seems this project uses SHA... that doesn't seem very good of an idea, especially for what this project is meant to achieve. I feel like ASIC resistance is important for this type of verification.

Something like Argon2, RandomX from Monero seem like better ideas, they're memory dependent functions that can't be ran on ASICs.

SHA isn't great as an algorithm for blockchains and PoW stuff, more so for verification and authentication.
Memory hard functions like the ones I mentioned are much better options, they can't be ran on ASICs, and can be customized to use specific amounts of RAM which would make it more noticeable to users if an application is doing something shady for example.

**Comment by ovx** [comment]
Hi, one important thing to note: **this project is not related to any blockchain or cryptocurrency**.  This is a CAPTCHA alternative and it's primary use is prevention of spam on websites. It uses SHA because those are the only hashing algorithms available in modern browsers and using SHA for this purpose is perfectly sufficient.

**Comment by juls0730** [comment]
web assembly isnt necessarily a requirement, you can use other hashing algorithms in JS, it would just be unbearably slow and harder to implement. While I have my own thoughts on WebAssembly and privacy concerns with it, that's neither here nor there, and I completely understand why you might want to block WASM.
