### ISSUE TITLE
Altcha svelte/sveltekit integration

### ISSUE THREAD

**Issue by bamthomas** [altcha-org/altcha#17]
First thank you for the library. 

We'd like to integrate it in our project that is already sveltekit/ts powered. 

For now we are doing:

```typescript
  onMount(async () => {
    await import('altcha');
  })
```

That is working on the client side. And we intent to reuse the express example in the backend code with the `altcha-lib`?

Is it a good way to do it? 
Do you know other project that would have done that? 
I've see for example that there is an `Altcha` component, is it accessible in a deliverable?

Thank you for your answers.

**Comment by ovx** [comment]
Hi,
yes, in SvelteKit, import it in onMount, but you should import only in the browser environment, otherwise the build will fail:

```ts
import { browser } from '$app/environment';

onMount(async () => {
  if (browser) {
    await import('altcha');
  }
});
```

The Svelte component is just for development, it's not distributed. You should use the WebComponent.

On the server-side, you can use the new library `altcha-lib` (the express example works as well, it just doesn't use the library).
