### ISSUE TITLE
Altcha-Widget stuck at "requesting server verification from"

### ISSUE THREAD

**Issue by vCoDMods** [altcha-org/altcha#52]
Hello,

i have setup an express server with own apikey etc. for Altcha-Widget. Without the "verifyurl=" it works normally, then i tried to add server verification, but it stucks at the request. Now i sit here for many hours and can´t find a solution.

my code for the validation:

`app.post('/validate_challenge', async (req, res) => {
  logger.info('validate_challenge endpoint hit');
  
  // Decode the Base64 payload and parse the JSON
  const payload = JSON.parse(Buffer.from(req.body, 'base64').toString('utf8'));
  
  if (!payload || !payload.challenge) {
    logger.warn('Invalid request: Missing payload or challenge');
    return res.status(400).json({ error: 'Invalid request' });
  }

  // Validate algorithm
  const alg_ok = payload.algorithm === 'SHA-256';

  // Validate challenge
  const challenge = crypto.createHash('sha256').update(payload.salt + payload.number).digest('hex');
  const challenge_ok = payload.challenge === challenge;

  // Validate signature
  const signature = crypto.createHmac('sha256', hmacKey).update(payload.challenge).digest('hex');
  const signature_ok = payload.signature === signature;

  // Validate expiration time
  const expires_ok = new Date() < new Date(payload.expires);

  // Consider the request verified if all checks are true
  const verified = alg_ok && challenge_ok && signature_ok && expires_ok;

  if (!verified) {
    return res.status(400).json({ error: 'Invalid ALTCHA solution' });
  }

  logger.info('Solution verified successfully');
  res.set('Content-Type', 'application/json'); // Set the 'Content-Type' header
  res.set('X-Verified', JSON.stringify({ verified: true })); // Send a response when the solution is verified successfully
  return res.status(200).send();
});`

**Comment by ovx** [comment]
Hi,
if you're using the SpamFilter with the API at eu.altcha.org or us.altcha.org, the payload received for verification changes - you no longer verify the challenge, that's done by the Spam Filter, you only verify the response from the API. This is documented here: https://altcha.org/docs/api/challenge-api/#server-verification

In short, instead of validating the challenge, you only [verify the signature](https://altcha.org/docs/api/challenge-api/#verifying-the-signature), where `hmac_key` is the secret part of the API key (`csec_...`):

```
// calculate SHA hash of the `verificationData`, unparsed, as they appear in the payload:
hash = sha2_hex(payload.verificationData);

// calculate HMAC signature
signature = hmac_sha2_hex(hash, hmac_key);
```
