### ISSUE TITLE
React-18 : Detail.payload is null on submit form

### ISSUE THREAD

**Issue by ayushgupta-1** [altcha-org/altcha#56]
Hello there,
I am trying to use the altcha-widget in React18 (Next14.2.3). 
I am using the code from [Stackblitz-react](https://stackblitz.com/~/github.com/altcha-org/altcha-starter-react-ts?file=src/Altcha.tsx), but I am facing an error when submitting the captcha for verification.

<img width="805" alt="Screenshot 2024-08-01 at 10 21 21 PM" src="https://github.com/user-attachments/assets/f9559a7d-19db-4984-a515-9fffc7f981eb">
          

The challenge successfully loads and can see in the console log but getting error when submitting the captcha.

<img width="963" alt="Screenshot 2024-08-01 at 10 11 32 PM" src="https://github.com/user-attachments/assets/84c377ee-858c-495b-b98b-bf1058733bf0">

<img width="963" alt="Screenshot 2024-08-01 at 10 11 32 PM" src="https://github.com/user-attachments/assets/33a02f85-9f6c-45e8-b5a2-5e366caab229">          

Could someone help in solving this issue ? 

Thanks.

**Comment by ovx** [comment]
Hi, the server returns 400, probably because the verification fails, else you need to debug your server; I see you're adding `verificationurl` - this property should be used only with the spam filter (it sends a different format of the payload); with custom server integrations, use only `challengeurl`, the altcha payload is supposed to be submitted with the form.
