### ISSUE TITLE
Setting maxnumber parameter on client

### ISSUE THREAD

**Issue by rspu** [altcha-org/altcha#64]
Hi

Thanks for this library. It looks really interesting.

I'm having some problem to understand how the complexity of the PoW can be set on the client side (e.g. through the widget) and a malicious spammer could not tamper with it by just calling the challenge endpoint with a very low complexity, receive and solve the easy challenge and submit it instead of the original challenge. 

The server endpoint verifying the challenge solution would not know that it is not the original challenge that was submitted. Were is my misunderstanding or would I have to take additional security measures to prevent it? (Like setting the `maxnumber` only on the server side)

Thanks

**Comment by ovx** [comment]
Hi, 
the verification process is designed to work with server-client workflows - the challenge must be always generated by the server which also signs the challenge with a secret. When signed, the client cannot temper with the challenge because the signature verification would fail. This means that the complexity cannot be set on the client, it is set only by the server.

The `maxnumber` attribute configured on the widget is there only to configure the upper limit in order to prevent infinite verification if something went wrong (such as incorrect challenge). But the actual complexity is controlled solely by the server.
