### ISSUE TITLE
Add Altcha as a Custom Provider for Firebase App Check

### ISSUE THREAD

**Issue by artrayd** [altcha-org/altcha#69]
I want to use Altcha as a custom provider for Firebase App Check.

Could you create an extension similar to this one?
https://extensions.dev/extensions/cloudflare/cloudflare-turnstile-app-check-provider

Here’s the Firebase App Check custom provider guide:
https://firebase.google.com/docs/app-check/custom-provider

Currently, Firebase App Check comes with reCaptcha as default provider, but there are two major issues:

1. It’s invisible, and if a user is not verified, there’s no way to display a visual challenge. In my case, I’ve seen about a 0.5% false-positive rate.
2. It’s not free, costing $1 per thousand requests.

I also tried Turnstile extension mentioned above, which is free, but it had another major issue: it’s also invisible and ended up blocking 20% of my users.

Altcha is our last hope, and we're working on implementing it now.
If we succeed, we'd be happy to share our implementation code with you.

**Comment by ovx** [comment]
Hi, you can try the new extension and client provider: https://github.com/altcha-org/firebase-app-check, the extension isn't published/verified yet, but you should be able to install it by clicking the link in the provider's readme. The default maxnumber is set to 10,000 - a low complexity is recommended because it's invisible (without any UI indicator), and solving bigger number would take too long on low-end devices.
